PROG4_HF/CloneArmy.Web/Models/Clone.cs
namespace CloneArmy.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    using Clone_Army.Data;

    /// <summary>
    /// Form model.
    /// </summary>
    public class Clone
    {
        /// <summary>
        /// Gets or sets the clone id.
        /// </summary>
        [Display(Name ="Clone Id")]
        [Required]
        public int Clone_ID { get; set; }

        /// <summary>
        /// Gets or sets the class id.
        /// </summary>
        [Display(Name = "Class Id")]
        [Required]
        public int Class_ID { get; set; }

        /// <summary>
        /// Gets or sets the armmy id.
        /// </summary>
        [Display(Name = "Army Id")]
        [Required]
        public int Army_ID { get; set; }

        /// <summary>
        /// Gets or sets the nickname of the clone.
        /// </summary>
        [Display(Name = "NickName")]
        [Required]
        public string NickName { get; set; }

        /// <summary>
        /// Gets or sets the name of the clone.
        /// </summary>
        [Display(Name = "Clone Serial Number")]
        [Required]
        [StringLength(10, MinimumLength = 7)]
        public string Name_ { get; set; }

        /// <summary>
        /// Gets or sets the birth date of the clone.
        /// </summary>
        [Display(Name = "Clone Birth date")]
        [Required]
        public string Birth_Date { get; set; }

        /// <summary>
        /// Gets or sets the speciality of the clone.
        /// </summary>
        [Display(Name = "Speciality")]
        [Required]
        public string Speciality { get; set; }

        /// <summary>
        /// Gets or sets the rank of the clone.
        /// </summary>
        [Display(Name = "The rank of the clone")]
        [Required]
        public string Ranks { get; set; }

        /// <summary>
        /// Gets or sets the army of the clone.
        /// </summary>
        [Display(Name = "The clone's army")]
        public virtual string ArmyName { get; set; }

        /// <summary>
        /// Gets or sets the class of the clone.
        /// </summary>
        [Display(Name = "The clone's class")]
        public virtual string ClassName { get; set; }
    }
}

PROG4_HF/CloneArmy.Web/Models/CloneViewModel.cs
namespace CloneArmy.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    /// <summary>
    /// Get the CloneViewModel.
    /// </summary>
    public class CloneViewModel
    {
        /// <summary>
        /// Gets or sets a clone that is edited.
        /// </summary>
        public Clone EditedClone { get; set; }

        /// <summary>
        /// Gets or sets a list of the clones in the database.
        /// </summary>
        public List<Clone> CloneList { get; set; }
    }
}

PROG4_HF/CloneArmy.Web/Models/Input.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using static Kaloriaszamlalo.Controllers.CalorieCounterController;

namespace Kaloriaszamlalo.Models
{
    public class Input
    {
        public string Name { get; set; }

        public double Weight { get; set; }

        public string exercise { get; set; }

        public double Length { get; set; }  
    }
}

PROG4_HF/CloneArmy.Web/Models/Output.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Kaloriaszamlalo.Models
{
    public class Output
    {
        public string Name { get; set; }

        public double Weight { get; set; }

        public double Length { get; set; }

        public double BurntCalorie { get; set; }
    }
}

PROG4_HF/CloneArmy.Web/Controllers/CloneController.cs
namespace CloneArmy.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using AutoMapper;
    using Clone_Army.Data;
    using Clone_Army.Logic;
    using Clone_Army.Repository;
    using CloneArmy.Web.Models;

    /// <summary>
    /// The main controller of the api.
    /// </summary>
    public class CloneController : Controller
    {
        private ILogic logic;
        private IMapper mapper;
        private CloneViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="CloneController"/> class.
        /// </summary>
        public CloneController()
        {
            CloneArmyDataEntities de = new CloneArmyDataEntities();
            Clone_Repository clone = new Clone_Repository();
            Army_Repository army = new Army_Repository();
            Class_Repository classes = new Class_Repository();
            this.logic = new Logic();
            this.mapper = MapperFactory.CreateMapper();
            this.vm = new CloneViewModel();
            this.vm.EditedClone = new CloneArmy.Web.Models.Clone();
            var clones = logic.GetAllCloneData();
            this.vm.CloneList = this.mapper.Map<IList<Clone_Army.Data.Clone>, List<Models.Clone>>(clones);
        }

        private CloneArmy.Web.Models.Clone GetCloneModel(int id)
        {
            Clone_Army.Data.Clone clone = this.logic.GetClone(id);
            return this.mapper.Map<Clone_Army.Data.Clone, Models.Clone>(clone);
        }

        /// <summary>
        /// Returns the Index page.
        /// </summary>
        /// <returns>ActionResult.</returns>
        // GET: Clone
        public ActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("CloneIndex", this.vm);
        }

        /// <summary>
        /// Returns the Details page.
        /// </summary>
        /// <param name="id">id.</param>
        /// <returns>ActionResult.</returns>
        // GET: Clone/Details/5
        public ActionResult Details(int id)
        {
            return this.View("CloneDetail", this.GetCloneModel(id));
        }

        /// <summary>
        /// Returns the Remove page.
        /// </summary>
        /// <param name="id">id.</param>
        /// <returns>ActionResult.</returns>
        // GET: /Clone/Remove/5
        public ActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAIL";
            if (this.logic.DeleteCloneData(id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction("Index");
        }

        // GET: /Clone/Edit/5
        public ActionResult Edit (int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedClone = this.GetCloneModel(id);
            return this.View("CloneIndex", this.vm);
        }

        /// <summary>
        /// Returns the Edit page.
        /// </summary>
        /// <param name="clone">clone.</param>
        /// <param name="editAction">editaction.</param>
        /// <returns>ActionResult.</returns>
        // POST /Clone/Edit + Clone + editAction
        [HttpPost]
        public ActionResult Edit(CloneArmy.Web.Models.Clone clone, string editAction)
        {
            if (this.ModelState.IsValid && clone != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    this.logic.InsertCloneData(clone.Clone_ID, clone.Class_ID, clone.Army_ID, clone.NickName, clone.Name_, clone.Speciality, clone.Birth_Date, clone.Ranks);
                }
                else
                {
                    bool success = this.logic.UpdateCloneData(clone.Clone_ID, clone.Clone_ID, clone.Class_ID, clone.Army_ID, clone.NickName, clone.Name_, clone.Speciality, clone.Birth_Date, clone.Ranks);
                    if (!success)
                    {
                        this.TempData["editResult"] = "Edit FAIL";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedClone = clone;
                return this.View("CloneIndex", this.vm);
            }
        }
    }
}

PROG4_HF/CloneArmy.Web/Views/Clone/CloneDetail.cshtml
@model CloneArmy.Web.Models.Clone
@{
    ViewBag.Title = "CloneDetail";
}

<h2>Datasheet of one clone</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Clone_ID)</td>
        <td>@Html.DisplayFor(m => m.Clone_ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Class_ID)</td>
        <td>@Html.DisplayFor(m => m.Class_ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Army_ID)</td>
        <td>@Html.DisplayFor(m => m.Army_ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name_)</td>
        <td>@Html.DisplayFor(m => m.Name_)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.NickName)</td>
        <td>@Html.DisplayFor(m => m.NickName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Birth_Date)</td>
        <td>@Html.DisplayFor(m => m.Birth_Date)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Speciality)</td>
        <td>@Html.DisplayFor(m => m.Speciality)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Ranks)</td>
        <td>@Html.DisplayFor(m => m.Ranks)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ClassName)</td>
        <td>@Html.DisplayFor(m => m.ClassName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ArmyName)</td>
        <td>@Html.DisplayFor(m => m.ArmyName)</td>
    </tr>
</table>

PROG4_HF/CloneArmy.Web/Views/Clone/CloneEdit.cshtml
@model CloneArmy.Web.Models.Clone

<h2>Edit one clone</h2>

@using (Html.BeginForm("Edit", "Clone"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Clone_ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());


    <div class="editor-label">@Html.LabelFor(m => m.Clone_ID)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Clone_ID)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Class_ID)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Class_ID)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Army_ID)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Army_ID)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Name_)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name_)</div>

    <div class="editor-label">@Html.LabelFor(m => m.NickName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.NickName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Speciality)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Speciality)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Birth_Date)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Birth_Date)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Ranks)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Ranks)</div>

    


    <input type="submit" value="SEND" />


}

PROG4_HF/CloneArmy.Web/Views/Clone/CloneIndex.cshtml
@model CloneArmy.Web.Models.CloneViewModel

@{
    ViewBag.Title = "Clone Index";
}

<h2>CloneIndex</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("CloneEdit", Model.EditedClone)

@Html.Partial("CloneList", Model.CloneList)

PROG4_HF/CloneArmy.Web/Views/Clone/CloneList.cshtml
@model IEnumerable<CloneArmy.Web.Models.Clone>

<h2>List of clones</h2>

@if (Model.Count()==0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().ArmyName)</th>
            <th>@Html.DisplayNameFor(m => m.First().Name_)</th>
            <th>DataSheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.ArmyName)</td>
            <td>@Html.DisplayFor(m => item.Name_)</td>
            <td>@Html.ActionLink("[SHOW]","Details", new { id = item.Clone_ID})</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Clone_ID })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Clone_ID })</td>
        </tr>
        }
    </table>
}

PROG4_HF/CloneArmy.Web/Views/Clone/Input.cshtml
@{
    ViewBag.Title = "Input";
}

<h2>Számold ki, mennyi kalóriát égetsz!</h2>


@if (TempData.ContainsKey("warning"))
{
    <p style="font-weight:bold;color:red">@TempData["warning"]</p>
}

    <form method="POST" action="/CalorieCounter/CalorieCount" id="calorie">
        <label>Sportoló neve:</label>
        <input type="text" name="Name" /> <br>
        <label>Sportoló súlya:</label>
        <input type="text" name="Weight" /> <br>
        <label for="exercise">Gyakorlat:</label>
        <select id="exercises" name="exercise">
            <option value="Running">Running</option>
            <option value="Yoga">Yoga</option>
            <option value="Pilates">Pilates</option>
            <option value="Hiking">Hiking</option>
            <option value="Swimming">Swimming</option>
            <option value="Bicycle">Bicycle</option>
        </select> <br>
        <label>Gyakorlat hossza (perc):</label>
        <input type="text" name="Length" /> <br>
        <input type="submit" value="Kiszámol" />
    </form>
   

PROG4_HF/CloneArmy.Web/Views/Clone/Output.cshtml
@model Kaloriaszamlalo.Models.Output
@{
    ViewBag.Title = "Output";
}

<h2>Az eredmény</h2>

<p>A sportoló neve @Model.Name</p>
<p>A sportoló tömege @Model.Weight</p>
<p>Gyakorlat hossza (perc) @Model.Length</p>
<p>Elégetett kalória @Model.BurntCalorie</p>